"use client";
import { useEffect,useMemo,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { ArrowLeft, BookOpen, Building2, CalendarDays, Check, ChevronRight, Edit3, Flame, Pin, RotateCcw, Sparkles, Target, Trash2 } from "lucide-react";
import { Badge, Button, Panel, Progress } from "@/components/ui";

const fallback = {
 source:{company:"Demo Company",company_url:"https://example.com",role:"Senior Software Engineer",location:"Remote",jd_chars:0,researched_at:new Date().toISOString(),pages_used:[]},
 company_brief:{summary:"Research-backed company summary will appear here after generation.",what_they_do:"The company research layer is ready to analyze the supplied website.",sources:[]},
 role:{title:"Senior Software Engineer",seniority:"Senior",responsibilities:["Build reliable software","Collaborate across teams"],requirements:[{id:"r1",text:"Strong software engineering fundamentals",kind:"technical",priority:"must"},{id:"r2",text:"Communicate and mentor effectively",kind:"behavioural",priority:"must"}]},
 questions:[
 {id:"q1",requirement_ids:["r1"],category:"technical",prompt:"How would you design a reliable service under production load?",answer_outline:"Discuss requirements, failure modes, observability, scaling and trade-offs.",difficulty:3},
 {id:"q2",requirement_ids:["r2"],category:"behavioural",prompt:"Tell me about a time you helped another engineer succeed.",answer_outline:"Use a concise situation, action, result and reflection structure.",difficulty:2}
 ],
 flashcards:[{id:"f1",front:"What makes a production service reliable?",back:"Clear SLOs, graceful failure, observability, testing, capacity planning and operational ownership.",requirement_ids:["r1"]},{id:"f2",front:"What makes mentoring effective?",back:"Specific feedback, context, autonomy, psychological safety and measurable growth.",requirement_ids:["r2"]}],
 schedule:{days_available:5,days:[1,2,3,4,5].map(day=>({day,focus:["Core technical depth","Behavioral stories","System design","Weak spots","Final review"][day-1],question_ids:[day===1?"q1":"q2"],minutes:45}))},
 coverage:{uncovered_requirement_ids:[],passes:2}
};

export default function Kit(){
 const {id}=useParams(); const router=useRouter(); const [kit,setKit]=useState<any>(null); const [tab,setTab]=useState("overview"); const [editing,setEditing]=useState<string|null>(null); const [draft,setDraft]=useState(""); const [practice,setPractice]=useState(0); const [revealed,setRevealed]=useState(false); const [confidence,setConfidence]=useState<number|null>(null);
 useEffect(()=>{const raw=sessionStorage.getItem(`kit-${id}`);if(raw)setKit(JSON.parse(raw));else setKit(fallback)},[id]);
 const k=kit||fallback; const covered=k.role.requirements.length-k.coverage.uncovered_requirement_ids.length; const coverage=Math.round(covered/Math.max(1,k.role.requirements.length)*100); const counts=useMemo(()=>({technical:k.questions.filter((q:any)=>q.category==="technical").length,behavioural:k.questions.filter((q:any)=>q.category==="behavioural").length,"system-design":k.questions.filter((q:any)=>q.category==="system-design").length,"company-fit":k.questions.filter((q:any)=>q.category==="company-fit").length}),[k]);
 function editQuestion(q:any){setEditing(q.id);setDraft(q.prompt)}
 function saveQuestion(q:any){const next={...k,questions:k.questions.map((x:any)=>x.id===q.id?{...x,prompt:draft}:x)};setKit(next);sessionStorage.setItem(`kit-${id}`,JSON.stringify(next));setEditing(null)}
 const weak=k.flashcards.slice().sort((a:any,b:any)=>0);
 return <main className="min-h-screen glow-bg">
  <header className="sticky top-0 z-30 border-b border-white/[.06] bg-[#07080d]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3"><button className="focus-ring flex items-center gap-2 text-sm text-muted hover:text-white" onClick={()=>router.push("/dashboard")}><ArrowLeft size={16}/> Kits</button><div className="flex items-center gap-3"><Badge tone="good">{coverage}% must-have coverage</Badge><Button variant="secondary" onClick={()=>setTab("practice")}><Flame size={15} className="mr-1 inline"/> Practice</Button></div></div></header>
  <div className="mx-auto max-w-7xl px-5 py-8">
   <div className="grid gap-5 lg:grid-cols-[1fr_300px]">
    <div><div className="text-xs uppercase tracking-[.18em] text-violet-300">{k.source.company}</div><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em]">{k.role.title}</h1><p className="mt-2 text-muted">{k.role.seniority} · {k.source.location||"Location not specified"} · {k.schedule.days_available} days to prepare</p></div>
    <Panel className="p-5"><div className="flex justify-between"><span className="text-xs uppercase tracking-wider text-muted">Interview readiness</span><Target size={16} className="text-violet-300"/></div><div className="mt-3 text-4xl font-semibold">{coverage}%</div><div className="mt-3"><Progress value={coverage}/></div><div className="mt-2 text-xs text-muted">{covered}/{k.role.requirements.length} requirements covered</div></Panel>
   </div>
   <div className="mt-8 flex gap-1 overflow-x-auto border-b border-white/[.06]">{["overview","company","role","questions","flashcards","schedule","practice"].map(t=><button key={t} onClick={()=>setTab(t)} className={`focus-ring whitespace-nowrap rounded-t-xl px-4 py-3 text-sm capitalize ${tab===t?"bg-white/[.05] text-white":"text-muted hover:text-white"}`}>{t}</button>)}</div>
   {tab==="overview"&&<div className="mt-6 grid gap-5 md:grid-cols-3"><Panel className="p-6 md:col-span-2"><div className="flex items-center gap-2 text-sm font-semibold"><Sparkles size={16} className="text-violet-300"/> Preparation snapshot</div><p className="mt-4 leading-7 text-white/65">{k.company_brief.summary}</p><div className="mt-6 grid grid-cols-3 gap-3">{Object.entries(counts).map(([a,b]:any)=><div className="rounded-xl border border-white/[.06] bg-white/[.02] p-4" key={a}><div className="text-xs uppercase text-muted">{a.replace("-"," ")}</div><div className="mt-2 text-2xl font-semibold">{b}</div></div>)}</div></Panel><Panel className="p-6"><div className="text-sm font-semibold">Next best action</div><div className="mt-5 rounded-xl bg-violet-400/[.07] p-4"><Flame size={18} className="text-violet-300"/><div className="mt-3 font-medium">Practice your weak spots</div><div className="mt-1 text-xs leading-5 text-muted">Confidence-weighted review keeps the next session focused.</div></div><Button className="mt-4 w-full" onClick={()=>setTab("practice")}>Start practice <ChevronRight size={15} className="ml-1 inline"/></Button></Panel></div>}
   {tab==="company"&&<div className="mt-6 grid gap-5 md:grid-cols-[1fr_320px]"><Panel className="p-6"><div className="flex items-center gap-2 font-semibold"><Building2 size={18} className="text-cyan-300"/> What they do</div><p className="mt-4 leading-7 text-white/65">{k.company_brief.what_they_do}</p><div className="mt-7 rounded-xl border border-white/[.06] bg-white/[.02] p-4"><div className="text-xs uppercase tracking-wider text-muted">Research note</div><p className="mt-2 text-sm text-white/55">{k.company_brief.sources.length?`Based on ${k.company_brief.sources.length} researched source(s).`:"Public hiring-process information was not found from configured sources."}</p></div></Panel><Panel className="p-6"><div className="text-sm font-semibold">Sources</div>{k.company_brief.sources.length?k.company_brief.sources.map((s:string)=><a className="mt-3 block truncate text-xs text-cyan-300 hover:underline" href={s} target="_blank" key={s}>{s}</a>):<div className="mt-4 text-sm text-muted">No external sources available.</div>}</Panel></div>}
   {tab==="role"&&<div className="mt-6 space-y-3">{k.role.requirements.map((r:any)=><Panel key={r.id} className="p-5"><div className="flex items-start gap-4"><div className="font-mono text-xs text-muted">{r.id}</div><div className="flex-1"><div className="font-medium">{r.text}</div><div className="mt-2 flex gap-2"><Badge tone={r.priority==="must"?"accent":"neutral"}>{r.priority}</Badge><Badge>{r.kind}</Badge><span className="text-xs text-muted">{k.questions.filter((q:any)=>q.requirement_ids.includes(r.id)).length} questions</span></div></div><Check size={17} className={k.coverage.uncovered_requirement_ids.includes(r.id)?"text-red-300":"text-emerald-300"}/></div></Panel>)}</div>}
   {tab==="questions"&&<div className="mt-6 space-y-3">{k.questions.map((q:any)=><Panel key={q.id} className="p-5"><div className="flex items-start gap-4"><div className="font-mono text-xs text-muted">{q.id}</div><div className="flex-1">{editing===q.id?<><textarea autoFocus className="focus-ring min-h-24 w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none" value={draft} onChange={e=>setDraft(e.target.value)}/><div className="mt-3 flex gap-2"><Button onClick={()=>saveQuestion(q)}>Save</Button><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button></div></>:<><div className="font-medium leading-6">{q.prompt}</div><div className="mt-3 flex flex-wrap gap-2"><Badge tone="accent">{q.category}</Badge><Badge>Difficulty {q.difficulty}</Badge>{q.requirement_ids.map((r:string)=><Badge key={r}>{r}</Badge>)}</div></>}</div>{editing!==q.id&&<div className="flex gap-1"><button className="focus-ring rounded-lg p-2 text-white/35 hover:bg-white/5 hover:text-white" onClick={()=>editQuestion(q)}><Edit3 size={15}/></button><button className="focus-ring rounded-lg p-2 text-white/35 hover:bg-white/5 hover:text-white"><Pin size={15}/></button></div>}</div></Panel>)}</div>}
   {tab==="flashcards"&&<div className="mx-auto mt-6 max-w-2xl"><FlashcardView card={k.flashcards[practice%k.flashcards.length]} revealed={revealed} setRevealed={setRevealed} confidence={confidence} setConfidence={setConfidence} onNext={()=>{setPractice(p=>p+1);setRevealed(false);setConfidence(null)}}/></div>}
   {tab==="practice"&&<div className="mx-auto mt-6 max-w-2xl"><div className="mb-4 text-sm text-muted">Weak Spots practice · card {practice%k.flashcards.length+1} of {k.flashcards.length}</div><FlashcardView card={k.flashcards[practice%k.flashcards.length]} revealed={revealed} setRevealed={setRevealed} confidence={confidence} setConfidence={setConfidence} onNext={()=>{setPractice(p=>p+1);setRevealed(false);setConfidence(null)}}/></div>}
   {tab==="schedule"&&<div className="mt-6 grid gap-3 md:grid-cols-2">{k.schedule.days.map((d:any)=><Panel className={`p-5 ${d.day===1?"border-violet-400/20":""}`} key={d.day}><div className="flex justify-between"><Badge tone={d.day===1?"accent":"neutral"}>Day {d.day}</Badge><span className="text-xs text-muted">{d.minutes} min</span></div><div className="mt-4 text-lg font-semibold capitalize">{d.focus}</div><div className="mt-3 flex flex-wrap gap-2">{d.question_ids.map((q:string)=><span className="rounded-lg bg-white/5 px-2 py-1 font-mono text-[11px] text-white/55" key={q}>{q}</span>)}</div></Panel>)}</div>}
  </div>
 </main>
}
function FlashcardView({card,revealed,setRevealed,confidence,setConfidence,onNext}:any){
 if(!card)return <Panel className="p-8">No flashcards yet.</Panel>;
 return <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="space-y-4"><Panel className="min-h-[360px] p-8"><div className="flex justify-between text-xs uppercase tracking-wider text-muted"><span>Flashcard</span><span>{card.requirement_ids.join(" · ")}</span></div><div className="flex min-h-[280px] flex-col items-center justify-center text-center"><BookOpen size={22} className="text-violet-300"/><div className="mt-7 max-w-xl text-2xl font-semibold leading-9">{revealed?card.back:card.front}</div>{!revealed&&<Button className="mt-8" onClick={()=>setRevealed(true)}>Reveal answer</Button>}</div></Panel>{revealed&&<Panel className="p-5"><div className="text-sm font-medium">How confident were you?</div><div className="mt-3 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setConfidence(n)} className={`focus-ring rounded-xl border py-3 text-sm ${confidence===n?"border-violet-400/40 bg-violet-400/10":"border-white/10 bg-white/[.02]"}`}>{n}</button>)}</div><Button className="mt-4 w-full" disabled={!confidence} onClick={onNext}>Next card <ChevronRight size={15} className="ml-1 inline"/></Button></Panel>}</motion.div>
}
